### ISSUE TITLE
"pip install apns3" installs the old package

### ISSUE THREAD

**Issue by adukic** [joshfriend/apns3#3]
apns3 package already exists on pypi, please refer to https://pypi.python.org/pypi/apns3. Can you please publish your package under different name and push to pypi.

**Comment by joshfriend** [comment]
`pip install apns` -> https://github.com/djacobs/PyAPNs
`pip install apns3` -> https://github.com/flamewow/PyAPNs (a fork of the former)

I have nothing to do with either project. Both still use the old v2 API, so I have no idea why one is called `apns3`. Perhaps because of more python3 compatibility modifications?

I have not published this to PyPI for several reasons:
1. The underlying http/2 library (`hyper`) is self described as being in ["early alpha"](https://hyper.readthedocs.io/en/latest/#caveat-emptor)
2. I have not even come close to trying this in production
3. I don't think I have completely figured out the requirements to be able to use the package (I'm not sure if it depends on python version or the openssl version python was compiled against)
4. There were a bunch of new features announced at WWDC 2016 that I wanted to include (#1, #2)
5. I don't feel like it is ready enough for me to commit to supporting it yet

I was able to send push notifications with this library in the current state the last time I was working on it (March 2016). You are more than welcome to still try it out though. Python packages can be installed from Git repos very easily:

```
pip install git+https://github.com/joshfriend/apns3#bb2210baad5fbec8f2505797e761da333f1e93f1
```
